import SwiftUI

struct AboutView: View {
    var body: some View {
        ZStack {
            if let bgImage = UIImage(named: "bg") {
                Image(uiImage: bgImage)
                    .resizable()
                    .edgesIgnoringSafeArea(.all)
            } else {
                Color.black.edgesIgnoringSafeArea(.all) 
                Text("Background image not available")
                    .foregroundColor(.white)
            }
            
            VStack {
                Spacer()
                
                Text("About Qrucible")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                    .foregroundColor(.white)
                    .padding(.bottom, 20)
                
                ScrollView {
                    Text("""
Qrucible is a versatile and user-friendly app designed to simplify the creation, saving, and management of QR codes. Whether you need to generate QR codes for links, text, or other data, Qrucible makes the process seamless and efficient.

**Key Features:**

- **Generate QR Codes:** Create high-quality QR codes by entering text or links. Qrucible generates your QR codes instantly.
- **Save QR Codes:** Organize your generated QR codes by saving them within the app. Each saved QR code retains its associated text or link for easy reference.
- **Download QR Codes:** Save your QR codes directly to your photo library for easy sharing and printing.
- **History View:** Access all your saved QR codes in one place. View details and manage your QR code history with ease.
- **User-Friendly Interface:** Enjoy a sleek and intuitive design that makes generating and managing QR codes a breeze.

Qrucible is perfect for businesses, educators, marketers, and anyone who needs a reliable QR code generator and manager.


**Disclaimer:**
Qrucible is provided as-is without any warranties. We do not take responsibility for any misuse of the QR codes generated by the app.
""")
                        .foregroundColor(.white)
                        .padding()
                }
                
                Spacer()
            }
            .padding()
        }
    }
}

#Preview {
    AboutView()
}
